# Generated by Django 5.1.4 on 2025-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personne_ressource',
            fields=[
                ('ID_PRessource', models.AutoField(db_column='ID_PRessource', primary_key=True, serialize=False)),
                ('prénom', models.CharField(blank=True, db_column='prénom', max_length=50, null=True)),
                ('Nom', models.CharField(blank=True, db_column='Nom', max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, db_column='telephone', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, db_column='sexe', max_length=20, null=True)),
                ('profession', models.CharField(blank=True, db_column='profession', max_length=50, null=True)),
                ('structure', models.CharField(blank=True, db_column='structure', max_length=50, null=True)),
                ('secteur_activité', models.CharField(blank=True, db_column='secteur_activité', max_length=50, null=True)),
                ('pays_de_residence', models.CharField(blank=True, db_column='pays_de_residence', max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
