name: Mon script toutes les 6 minutes

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Annuaire
          MYSQL_DATABASE: the_okwelians
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASSWORD: Annuaire
          MYSQL_DATABASE: the_okwelians
        run: python Synchronisation.py

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Recreate credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > service_account.json

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Exécuter le script
        run: |
          python Synchronisation.py
